Server:
  name: "bi-server"
  port: 8080

Database:
  host: 127.0.0.1
  port: 3306
  user: root
  password: 123456
  db: test
  charset: utf8mb4

Redis:
  network: 127.0.0.1
  addr: 6379
  password: ""
  read_timeout: 5
  write_timeout: 5

Jwt: